# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build
      - run: npm run build


      # deploy
      - deploy:
          name: Trigger Deployment
          command: |
            echo 'Changes: '
            git status -sb
            ls -la
            if [[ $(git diff --stat) != '' ]]; then
              echo 'dirty - lets push'
              git config credential.helper 'cache --timeout=120'
              git config user.email "circleci@circleci.com"
              git config user.name "Deployment Bot"
              npm version --no-git-tag-version patch
              git add .
              git commit -m "CircleCI Trigger Autobuild `date` for branch=${CIRCLE_BRANCH}"
              git push -q https://${GITHUB_TOKEN}@github.com/synle/synle.github.io "${CIRCLE_BRANCH}"
            else
              echo 'clean no update'
            fi
