name: main-build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master, main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[CI Build]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is available

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci # More reliable than 'npm install'

      - name: Build project
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '[CI Build] - Prettier & LESS build & PDF generation [skip ci]'
          add: '.'
